### profile may optionally select or skip tests

# # (optional) list included tests here:
tests: 
        - B101  # B101    assert_used
        - B102  # B102    exec_used
        - B103  # B103    set_bad_file_permissions
        - B104  # B104    hardcoded_bind_all_interfaces
        - B105  # B105    hardcoded_password_string
        - B106  # B106    hardcoded_password_funcarg
        - B107  # B107    hardcoded_password_default
        - B108  # B108    hardcoded_tmp_directory
        - B110  # B110    try_except_pass
        - B112  # B112    try_except_continue
        - B201  # B201    flask_debug_true
        - B301  # B301    pickle
        - B302  # B302    marshal
        - B303  # B303    md5
        - B304  # B304    ciphers
        - B305  # B305    cipher_modes
        - B306  # B306    mktemp_q
        - B307  # B307    eval
        - B308  # B308    mark_safe
        - B309  # B309    httpsconnection
        - B310  # B310    urllib_urlopen
        - B311  # B311    random
        - B312  # B312    telnetlib
        - B313  # B313    xml_bad_cElementTree
        - B314  # B314    xml_bad_ElementTree
        - B315  # B315    xml_bad_expatreader
        - B316  # B316    xml_bad_expatbuilder
        - B317  # B317    xml_bad_sax
        - B318  # B318    xml_bad_minidom
        - B319  # B319    xml_bad_pulldom
        - B320  # B320    xml_bad_etree
        - B321  # B321    ftplib
        - B322  # B322    input
        - B323  # B323    unverified_context
        - B324  # B324    hashlib_new_insecure_functions
        - B325  # B325    tempnam
        - B401  # B401    import_telnetlib
        - B402  # B402    import_ftplib
        - B403  # B403    import_pickle
        # this tool uses subprocess to execute commands
        # - B404  # B404    import_subprocess
        - B405  # B405    import_xml_etree
        - B406  # B406    import_xml_sax
        - B407  # B407    import_xml_expat
        - B408  # B408    import_xml_minidom
        - B409  # B409    import_xml_pulldom
        - B410  # B410    import_lxml
        - B411  # B411    import_xmlrpclib
        - B412  # B412    import_httpoxy
        - B413  # B413    import_pycrypto
        - B501  # B501    request_with_no_cert_validation
        - B502  # B502    ssl_with_bad_version
        - B503  # B503    ssl_with_bad_defaults
        - B504  # B504    ssl_with_no_version
        - B505  # B505    weak_cryptographic_key
        - B506  # B506    yaml_load
        - B507  # B507    ssh_no_host_key_verification
        - B601  # B601    paramiko_calls
        - B602  # B602    subprocess_popen_with_shell_equals_true
        # allow commands._common.call_subprocess to accept string command
        # - B603  # B603    subprocess_without_shell_equals_true
        # - B604  # B604    any_other_function_with_shell_equals_true
        - B605  # B605    start_process_with_a_shell
        - B606  # B606    start_process_with_no_shell
        - B607  # B607    start_process_with_partial_path
        - B608  # B608    hardcoded_sql_expressions
        - B609  # B609    linux_commands_wildcard_injection
        - B610  # B610    django_extra_used
        - B611  # B611    django_rawsql_used
        - B701  # B701    jinja2_autoescape_false
        - B702  # B702    use_of_mako_templates
        - B703  # B703    django_mark_safe    

# # (optional) list skipped tests here:
# skips: 
#     - B101
#     - B601

